---
title:         Capstone Project
author:        Ainesh Pandey, Caroline Shi, Vaishnavi Vadlamani, Annamalai Kathirkamanathan
date created:  September 9, 2017
date modified: October 25, 2017
---

```{r echo=FALSE, warning=FALSE}

setwd("~/Desktop/Semester 3/Capstone/BBCcapstone")

```

```{r}

# Update - 9/27

# load initial dataset
dataset <- read.csv("Final Dataset_LimitedCountries_first_sales.csv")

# remove all CLIPS from dataset (they add too many outliers)
dataset = subset(dataset, SalesType != 'CLIPS')

# drop BusinessArea, SalesType columns,, Firstsale (dummy variable for them already exists - SalesType_Clips is not required)
dataset <- dataset[, !(names(dataset) %in% c('CustomerName', 'CustomerId', 'BusinessArea', 'SalesType', 'FirstSale', 'SalesType_CLIPS'))]

# add column TotalLengthOfContent to dataset
dataset$TotalLengthOfContent <- with(dataset, EpisodeLengthmin*TotalNumberOfEpisodes)

# add column AgeOfContent to dataset
dataset$AgeOfContent <- with(dataset, as.Date(DateOfDeal,"%m/%d/%Y")-as.Date(DateOfPremier,"%m/%d/%Y"))

# Change difftime to numeric
dataset$AgeOfContent <- as.numeric(dataset$AgeOfContent)

#To view the mapping of names to numerical values
#library(gdata)
#mapLevels(x=dataset$MediaType)

# Convert media type to numeric values
#dataset$MediaType <- as.numeric(dataset$MediaType)

#Convert rating to numeric
#dataset$Rated <- as.numeric(dataset$Rated)

# Creating dummies for media type and rated
mediatype.factor <- factor(dataset$MediaType)
dummies_mediatype = model.matrix(~mediatype.factor)
#dummies_mediatype <- dummies_mediatype[, !(names(dummies_mediatype) %in% c('(Intercept)'))]

rated.factor <- factor(dataset$Rated)
dummies_rated = model.matrix(~rated.factor)
#dummies_rated <- dummies_rated[, !(names(dummies_rated) %in% c('(Intercept)'))]

# Binding it with genome dataframe
dataset <- cbind(dataset,dummies_mediatype,dummies_rated)


# Drop date columns
genome_data <- dataset[, !(names(dataset) %in% c('DateOfDeal', 'DateOfPremier', 'EpisodeLengthmin', 'TotalNumberOfEpisodes', 'MediaType', 'Rated', '(Intercept)'))]

# Reordering column Media type
#index_mediatype <- grep("MediaType", names(genome_data))
#genome_data <- genome_data[, c(1:2,4:5,index_mediatype,(6:ncol(genome_data)))]

# Demeaning the data - Update 10/23

# Step 1 - LN (revenue)
genome_data$logRevenue <- log(genome_data$Revenue)
# Step 2 - Season avg log revenue
season_avgRevenue <- aggregate(genome_data[,79], list(genome_data$TitleName), mean)
library(plyr)
season_avgRevenue <- rename(season_avgRevenue,c("Group.1" = "TitleName", "x" = "AvgLogRevenuePerSeason"))
genome_data_demean <- merge(genome_data,season_avgRevenue,by = "TitleName",all.x = TRUE)
# Step 3 - Demeanded log revenue
genome_data_demean$demeanedLogRevenue <- genome_data_demean$logRevenue - genome_data_demean$AvgLogRevenuePerSeason

# extract datasets by country from demeaned dataset
datasets_country <- split(genome_data_demean, f=genome_data_demean$final_country)

# Log normalization
#normalize_log2 <- function(x) { ifelse(abs(x) <= 1, 0, sign(x)*log2(abs(x))) }

# Normalize all numerical columns of each country

# 6:15 - NumberOfEpisodesSold, TotalNumberOfSeasons, calm2D, fear1D, shame1D, like2D, surprise1D, sure2D, anger1D, happy2D
# 40:41 - MainCharacterNumber, GenderRatio
# 50:68 - All Thoughtly variables
# 75:76 - TotalLengthOfContent, AgeOfContent

for (i in 1:length(datasets_country)) {
  datasets_country[[i]][,c(6:15,40:41,50:68,75:76)] <- apply(datasets_country[[i]][,c(6:15,40:41,50:68,75:76)], 2, scale, center=TRUE, scale=TRUE)
}

#datasets_country is a list of dataframes that has the genome information of each country.

```

